export interface ProcessorState {
  id: number
  abnormalHeightLevel: number
  closeAverage: number
  color0: number
  colorGreaterThanMinus1: boolean
  colorLessThan1: boolean
  flowSizeGreaterThan4: boolean
  freq: number
  getColorMax: number
  getColorMin: number
  high0: number
  high0GreaterThanMaxValue: boolean
  high0GreatherThanMinValid: boolean
  high0MinusLow0: number
  high1: number
  high2: number
  high3: number
  high4: number
  idTick: number
  idcontract: number
  isEventTypeMaxConfirm: boolean
  isEventTypeMaxDetect: boolean
  isEventTypeMaxDetectCancel: boolean
  isEventTypeMinConfirm: boolean
  isEventTypeMinDetect: boolean
  isEventTypeMinDetectCancel: boolean
  isHigh1LessThanOrEqualHigh2: boolean
  isHigh2LessThanMax: boolean
  isHigh3LessThanOrEqualHigh2: boolean
  isHigh4LessThanOrEqualHigh2: boolean
  isLow1GreaterThanOrEqualLow2: boolean
  isLow2GreatherThanMin: boolean
  isLow3GreaterThanOrEqualLow2: boolean
  isLow4GreaterThanOrEqualLow2: boolean
  isMaxDetect: boolean
  isMinDetect: boolean
  isNewCandle: boolean
  low0: number
  low0LessThanMaxValid: number
  low0LessThanMinValue: number
  low1: number
  low2: number
  low3: number
  low4: number
  max: number
  maxTrend: boolean
  maxValid: number
  maxValue: number
  min: number
  minTrend: boolean
  minValue: number
  minValid: number
  offset_: number
  smallCandleNoiseRemoval: boolean
  timestamp: Date


}
